### ISSUE TITLE
Not able to build with the plugin

### ISSUE THREAD

**Issue by saifkamaal** [mjwheatley/cordova-plugin-android-fingerprint-auth#84]
Hi,

I am trying to consume the cordova plugin in our Oracle MAF application however i am not able to build the project once i add the plugin to my project.

The following error is displayed. Any pointers ?

[11:14:06 AM] Installing "cordova-plugin-android-fingerprint-auth" for android
[11:14:06 AM] Error during processing of action! Attempting to revert...
[11:14:06 AM] Failed to install 'cordova-plugin-android-fingerprint-auth':Error: Uh oh!
[11:14:06 AM] "/Users/saifkamaal/jdeveloper/mywork/FingerPrintMAF/deploy/Android1/android_template/app/res/values-it" already exists!
[11:14:06 AM] at Object.module.exports.common.copyNewFile (/Users/saifkamaal/Oracle/Middleware12.2.1.0/jdeveloper/jdev/extensions/oracle.maf/tools/plugman/node_modules/plugman/node_modules/cordova-lib/src/plugman/platforms/common.js:67:19)
[11:14:06 AM] at Object.module.exports.source-file.install (/Users/saifkamaal/Oracle/Middleware12.2.1.0/jdeveloper/jdev/extensions/oracle.maf/tools/plugman/node_modules/plugman/node_modules/cordova-lib/src/plugman/platforms/android.js:78:20)
[11:14:06 AM] at installWrapper (/Users/saifkamaal/Oracle/Middleware12.2.1.0/jdeveloper/jdev/extensions/oracle.maf/tools/plugman/node_modules/plugman/node_modules/cordova-lib/src/platforms/platforms.js:77:32)
[11:14:06 AM] at Object.ActionStack.process (/Users/saifkamaal/Oracle/Middleware12.2.1.0/jdeveloper/jdev/extensions/oracle.maf/tools/plugman/node_modules/plugman/node_modules/cordova-lib/src/plugman/util/action-stack.js:68:25)
[11:14:06 AM] at handleInstall (/Users/saifkamaal/Oracle/Middleware12.2.1.0/jdeveloper/jdev/extensions/oracle.maf/tools/plugman/node_modules/plugman/node_modules/cordova-lib/src/plugman/install.js:576:20)
[11:14:06 AM] at /Users/saifkamaal/Oracle/Middleware12.2.1.0/jdeveloper/jdev/extensions/oracle.maf/tools/plugman/node_modules/plugman/node_modules/cordova-lib/src/plugman/install.js:368:24
[11:14:06 AM] at _fulfilled (/Users/saifkamaal/Oracle/Middleware12.2.1.0/jdeveloper/jdev/extensions/oracle.maf/tools/plugman/node_modules/plugman/node_modules/q/q.js:787:54)
[11:14:06 AM] at self.promiseDispatch.done (/Users/saifkamaal/Oracle/Middleware12.2.1.0/jdeveloper/jdev/extensions/oracle.maf/tools/plugman/node_modules/plugman/node_modules/q/q.js:816:30)
[11:14:06 AM] at Promise.promise.promiseDispatch (/Users/saifkamaal/Oracle/Middleware12.2.1.0/jdeveloper/jdev/extensions/oracle.maf/tools/plugman/node_modules/plugman/node_modules/q/q.js:749:13)
[11:14:06 AM] at /Users/saifkamaal/Oracle/Middleware12.2.1.0/jdeveloper/jdev/extensions/oracle.maf/tools/plugman/node_modules/plugman/node_modules/q/q.js:557:44
[11:14:06 AM] Uh oh!

Minimum SDK Level: 19 also tried with 23
Build Tools: 25.0.2

**Comment by mjwheatley** [comment]
Do you already have a values-it folder for Italian translations or any other languages in your project?

**Comment by mjwheatley** [comment]
Maybe try using --force

`cordova plugin add --force `

Introduced in version 6.1. Forces copying source files from the plugin even if the same file already exists in the target directory.

**Comment by saifkamaal** [comment]
The error was due to the way Oracle MAF builds the apk - which has been resolved.

Thnks
